# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/todo_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/todo_service.proto',
  package='todo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19protos/todo_service.proto\x12\x04todo\"\x1b\n\rAuthorRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"*\n\x0e\x41uthorResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t2@\n\x06\x41uthor\x12\x36\n\tGetAuthor\x12\x13.todo.AuthorRequest\x1a\x14.todo.AuthorResponseb\x06proto3'
)




_AUTHORREQUEST = _descriptor.Descriptor(
  name='AuthorRequest',
  full_name='todo.AuthorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo.AuthorRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=62,
)


_AUTHORRESPONSE = _descriptor.Descriptor(
  name='AuthorResponse',
  full_name='todo.AuthorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo.AuthorResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='todo.AuthorResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['AuthorRequest'] = _AUTHORREQUEST
DESCRIPTOR.message_types_by_name['AuthorResponse'] = _AUTHORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthorRequest = _reflection.GeneratedProtocolMessageType('AuthorRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORREQUEST,
  '__module__' : 'protos.todo_service_pb2'
  # @@protoc_insertion_point(class_scope:todo.AuthorRequest)
  })
_sym_db.RegisterMessage(AuthorRequest)

AuthorResponse = _reflection.GeneratedProtocolMessageType('AuthorResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORRESPONSE,
  '__module__' : 'protos.todo_service_pb2'
  # @@protoc_insertion_point(class_scope:todo.AuthorResponse)
  })
_sym_db.RegisterMessage(AuthorResponse)



_AUTHOR = _descriptor.ServiceDescriptor(
  name='Author',
  full_name='todo.Author',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=108,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAuthor',
    full_name='todo.Author.GetAuthor',
    index=0,
    containing_service=None,
    input_type=_AUTHORREQUEST,
    output_type=_AUTHORRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHOR)

DESCRIPTOR.services_by_name['Author'] = _AUTHOR

# @@protoc_insertion_point(module_scope)
